version: '3.8'
services:
  postgres:
    image: 'timescale/timescaledb:latest-pg17'  # TimescaleDB'nin PostgreSQL 17 sürümü
    container_name: 'inbest-db'
    environment:
      POSTGRES_DB: 'inbestDB'
      POSTGRES_PASSWORD: 'inbest'
      POSTGRES_USER: 'inbest'
    ports:
      - '5432:5432'
    volumes:
      - 'postgres-data:/var/lib/postgresql/data'
    restart: always  # PostgreSQL'in çökmesi durumunda otomatik başlatır

volumes:
  postgres-data:
