CREATE TABLE Portfolio (
    PortfolioID SERIAL PRIMARY KEY,
    PortfolioName VARCHAR(100) NOT NULL,
    CreatedDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    LastUpdatedDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UserID INT NOT NULL,
    Visibility VARCHAR(10) DEFAULT 'private',
    CONSTRAINT fk_user FOREIGN KEY (UserID) REFERENCES Users (id) ON DELETE CASCADE
);
