CREATE TABLE StockPrice (
    PriceID SERIAL PRIMARY KEY,
    StockID INT NOT NULL,
    Price DECIMAL(10, 2) NOT NULL,
    Date TIMESTAMP NOT NULL,
    CONSTRAINT fk_stock FOREIGN KEY (StockID) REFERENCES Stock (StockID) ON DELETE CASCADE
);
