TRUNCATE TABLE stock RESTART IDENTITY CASCADE;

INSERT INTO stock (ticker_symbol, stock_name, current_price) VALUES
                                                                 ('MMM', '3M', 0),
                                                                 ('AOS', 'A. O. Smith', 0),
                                                                 ('ABT', 'Abbott Laboratories', 0),
                                                                 ('ABBV', 'AbbVie', 0),
                                                                 ('ACN', 'Accenture', 0),
                                                                 ('ADBE', 'Adobe Inc.', 0),
                                                                 ('AMD', 'Advanced Micro Devices', 0),
                                                                 ('AES', 'AES Corporation', 0),
                                                                 ('AFL', 'Aflac', 0),
                                                                 ('A', 'Agilent Technologies', 0),
                                                                 ('APD', 'Air Products', 0),
                                                                 ('ABNB', 'Airbnb', 0),
                                                                 ('AKAM', 'Akamai Technologies', 0),
                                                                 ('ALB', 'Albemarle Corporation', 0),
                                                                 ('ARE', 'Alexandria Real Estate Equities', 0),
                                                                 ('ALGN', 'Align Technology', 0),
                                                                 ('ALLE', 'Allegion', 0),
                                                                 ('LNT', 'Alliant Energy', 0),
                                                                 ('ALL', 'Allstate', 0),
                                                                 ('GOOGL', 'Alphabet Inc. (Class A)', 0),
                                                                 ('GOOG', 'Alphabet Inc. (Class C)', 0),
                                                                 ('MO', 'Altria', 0),
                                                                 ('AMZN', 'Amazon', 0),
                                                                 ('AMCR', 'Amcor', 0),
                                                                 ('AEE', 'Ameren', 0),
                                                                 ('AEP', 'American Electric Power', 0),
                                                                 ('AXP', 'American Express', 0),
                                                                 ('AIG', 'American International Group', 0),
                                                                 ('AMT', 'American Tower', 0),
                                                                 ('AWK', 'American Water Works', 0),
                                                                 ('AMP', 'Ameriprise Financial', 0),
                                                                 ('AME', 'Ametek', 0),
                                                                 ('AMGN', 'Amgen', 0),
                                                                 ('APH', 'Amphenol', 0),
                                                                 ('ADI', 'Analog Devices', 0),
                                                                 ('ANSS', 'Ansys', 0),
                                                                 ('AON', 'Aon plc', 0),
                                                                 ('APA', 'APA Corporation', 0),
                                                                 ('APO', 'Apollo Global Management', 0),
                                                                 ('AAPL', 'Apple Inc.', 0),
                                                                 ('AMAT', 'Applied Materials', 0),
                                                                 ('APTV', 'Aptiv', 0),
                                                                 ('ACGL', 'Arch Capital Group', 0),
                                                                 ('ADM', 'Archer Daniels Midland', 0),
                                                                 ('ANET', 'Arista Networks', 0),
                                                                 ('AJG', 'Arthur J. Gallagher & Co.', 0),
                                                                 ('AIZ', 'Assurant', 0),
                                                                 ('T', 'AT&T', 0),
                                                                 ('ATO', 'Atmos Energy', 0),
                                                                 ('ADSK', 'Autodesk', 0),
                                                                 ('ADP', 'Automatic Data Processing', 0),
                                                                 ('AZO', 'AutoZone', 0),
                                                                 ('AVB', 'AvalonBay Communities', 0),
                                                                 ('AVY', 'Avery Dennison', 0),
                                                                 ('AXON', 'Axon Enterprise', 0),
                                                                 ('BKR', 'Baker Hughes', 0),
                                                                 ('BALL', 'Ball Corporation', 0),
                                                                 ('BAC', 'Bank of America', 0),
                                                                 ('BAX', 'Baxter International', 0),
                                                                 ('BDX', 'Becton Dickinson', 0),
                                                                 ('BRK.B', 'Berkshire Hathaway', 0),
                                                                 ('BBY', 'Best Buy', 0),
                                                                 ('TECH', 'Bio-Techne', 0),
                                                                 ('BIIB', 'Biogen', 0),
                                                                 ('BLK', 'BlackRock', 0),
                                                                 ('BX', 'Blackstone Inc.', 0),
                                                                 ('BK', 'BNY Mellon', 0),
                                                                 ('BA', 'Boeing', 0),
                                                                 ('BKNG', 'Booking Holdings', 0),
                                                                 ('BWA', 'BorgWarner', 0),
                                                                 ('BSX', 'Boston Scientific', 0),
                                                                 ('BMY', 'Bristol Myers Squibb', 0),
                                                                 ('AVGO', 'Broadcom', 0),
                                                                 ('BR', 'Broadridge Financial Solutions', 0),
                                                                 ('BRO', 'Brown & Brown', 0),
                                                                 ('BF.B', 'Brown–Forman', 0),
                                                                 ('BLDR', 'Builders FirstSource', 0),
                                                                 ('BG', 'Bunge Global', 0),
                                                                 ('BXP', '"BXP', 0),
                                                                 ('CHRW', 'C.H. Robinson', 0),
                                                                 ('CDNS', 'Cadence Design Systems', 0),
                                                                 ('CZR', 'Caesars Entertainment', 0),
                                                                 ('CPT', 'Camden Property Trust', 0),
                                                                 ('CPB', 'Campbell''s Company (The)', 0),
('COF', 'Capital One', 0),
('CAH', 'Cardinal Health', 0),
('KMX', 'CarMax', 0),
('CCL', 'Carnival', 0),
('CARR', 'Carrier Global', 0),
('CAT', 'Caterpillar Inc.', 0),
('CBOE', 'Cboe Global Markets', 0),
('CBRE', 'CBRE Group', 0),
('CDW', 'CDW Corporation', 0),
('CE', 'Celanese', 0),
('COR', 'Cencora', 0),
('CNC', 'Centene Corporation', 0),
('CNP', 'CenterPoint Energy', 0),
('CF', 'CF Industries', 0),
('CRL', 'Charles River Laboratories', 0),
('SCHW', 'Charles Schwab Corporation', 0),
('CHTR', 'Charter Communications', 0),
('CVX', 'Chevron Corporation', 0),
('CMG', 'Chipotle Mexican Grill', 0),
('CB', 'Chubb Limited', 0),
('CHD', 'Church & Dwight', 0),
('CI', 'Cigna', 0),
('CINF', 'Cincinnati Financial', 0),
('CTAS', 'Cintas', 0),
('CSCO', 'Cisco', 0),
('C', 'Citigroup', 0),
('CFG', 'Citizens Financial Group', 0),
('CLX', 'Clorox', 0),
('CME', 'CME Group', 0),
('CMS', 'CMS Energy', 0),
('KO', 'Coca-Cola Company (The)', 0),
('CTSH', 'Cognizant', 0),
('CL', 'Colgate-Palmolive', 0),
('CMCSA', 'Comcast', 0),
('CAG', 'Conagra Brands', 0),
('COP', 'ConocoPhillips', 0),
('ED', 'Consolidated Edison', 0),
('STZ', 'Constellation Brands', 0),
('CEG', 'Constellation Energy', 0),
('COO', 'Cooper Companies (The)', 0),
('CPRT', 'Copart', 0),
('GLW', 'Corning Inc.', 0),
('CPAY', 'Corpay', 0),
('CTVA', 'Corteva', 0),
('CSGP', 'CoStar Group', 0),
('COST', 'Costco', 0),
('CTRA', 'Coterra', 0),
('CRWD', 'CrowdStrike', 0),
('CCI', 'Crown Castle', 0),
('CSX', 'CSX Corporation', 0),
('CMI', 'Cummins', 0),
('CVS', 'CVS Health', 0),
('DHR', 'Danaher Corporation', 0),
('DRI', 'Darden Restaurants', 0),
('DVA', 'DaVita', 0),
('DAY', 'Dayforce', 0),
('DECK', 'Deckers Brands', 0),
('DE', 'Deere & Company', 0),
('DELL', 'Dell Technologies', 0),
('DAL', 'Delta Air Lines', 0),
('DVN', 'Devon Energy', 0),
('DXCM', 'Dexcom', 0),
('FANG', 'Diamondback Energy', 0),
('DLR', 'Digital Realty', 0),
('DFS', 'Discover Financial', 0),
('DG', 'Dollar General', 0),
('DLTR', 'Dollar Tree', 0),
('D', 'Dominion Energy', 0),
('DPZ', 'Domino''s', 0),
                                                                 ('DOV', 'Dover Corporation', 0),
                                                                 ('DOW', 'Dow Inc.', 0),
                                                                 ('DHI', 'D. R. Horton', 0),
                                                                 ('DTE', 'DTE Energy', 0),
                                                                 ('DUK', 'Duke Energy', 0),
                                                                 ('DD', 'DuPont', 0),
                                                                 ('EMN', 'Eastman Chemical Company', 0),
                                                                 ('ETN', 'Eaton Corporation', 0),
                                                                 ('EBAY', 'eBay Inc.', 0),
                                                                 ('ECL', 'Ecolab', 0),
                                                                 ('EIX', 'Edison International', 0),
                                                                 ('EW', 'Edwards Lifesciences', 0),
                                                                 ('EA', 'Electronic Arts', 0),
                                                                 ('ELV', 'Elevance Health', 0),
                                                                 ('EMR', 'Emerson Electric', 0),
                                                                 ('ENPH', 'Enphase Energy', 0),
                                                                 ('ETR', 'Entergy', 0),
                                                                 ('EOG', 'EOG Resources', 0),
                                                                 ('EPAM', 'EPAM Systems', 0),
                                                                 ('EQT', 'EQT Corporation', 0),
                                                                 ('EFX', 'Equifax', 0),
                                                                 ('EQIX', 'Equinix', 0),
                                                                 ('EQR', 'Equity Residential', 0),
                                                                 ('ERIE', 'Erie Indemnity', 0),
                                                                 ('ESS', 'Essex Property Trust', 0),
                                                                 ('EL', 'Estée Lauder Companies (The)', 0),
                                                                 ('EG', 'Everest Group', 0),
                                                                 ('EVRG', 'Evergy', 0),
                                                                 ('ES', 'Eversource Energy', 0),
                                                                 ('EXC', 'Exelon', 0),
                                                                 ('EXPE', 'Expedia Group', 0),
                                                                 ('EXPD', 'Expeditors International', 0),
                                                                 ('EXR', 'Extra Space Storage', 0),
                                                                 ('XOM', 'ExxonMobil', 0),
                                                                 ('FFIV', '"F5', 0),
                                                                 ('FDS', 'FactSet', 0),
                                                                 ('FICO', 'Fair Isaac', 0),
                                                                 ('FAST', 'Fastenal', 0),
                                                                 ('FRT', 'Federal Realty Investment Trust', 0),
                                                                 ('FDX', 'FedEx', 0),
                                                                 ('FIS', 'Fidelity National Information Services', 0),
                                                                 ('FITB', 'Fifth Third Bancorp', 0),
                                                                 ('FSLR', 'First Solar', 0),
                                                                 ('FE', 'FirstEnergy', 0),
                                                                 ('FI', 'Fiserv', 0),
                                                                 ('FMC', 'FMC Corporation', 0),
                                                                 ('F', 'Ford Motor Company', 0),
                                                                 ('FTNT', 'Fortinet', 0),
                                                                 ('FTV', 'Fortive', 0),
                                                                 ('FOXA', 'Fox Corporation (Class A)', 0),
                                                                 ('FOX', 'Fox Corporation (Class B)', 0),
                                                                 ('BEN', 'Franklin Resources', 0),
                                                                 ('FCX', 'Freeport-McMoRan', 0),
                                                                 ('GRMN', 'Garmin', 0),
                                                                 ('IT', 'Gartner', 0),
                                                                 ('GE', 'GE Aerospace', 0),
                                                                 ('GEHC', 'GE HealthCare', 0),
                                                                 ('GEV', 'GE Vernova', 0),
                                                                 ('GEN', 'Gen Digital', 0),
                                                                 ('GNRC', 'Generac', 0),
                                                                 ('GD', 'General Dynamics', 0),
                                                                 ('GIS', 'General Mills', 0),
                                                                 ('GM', 'General Motors', 0),
                                                                 ('GPC', 'Genuine Parts Company', 0),
                                                                 ('GILD', 'Gilead Sciences', 0),
                                                                 ('GPN', 'Global Payments', 0),
                                                                 ('GL', 'Globe Life', 0),
                                                                 ('GDDY', 'GoDaddy', 0),
                                                                 ('GS', 'Goldman Sachs', 0),
                                                                 ('HAL', 'Halliburton', 0),
                                                                 ('HIG', 'Hartford (The)', 0),
                                                                 ('HAS', 'Hasbro', 0),
                                                                 ('HCA', 'HCA Healthcare', 0),
                                                                 ('DOC', 'Healthpeak Properties', 0),
                                                                 ('HSIC', 'Henry Schein', 0),
                                                                 ('HSY', 'Hershey Company (The)', 0),
                                                                 ('HES', 'Hess Corporation', 0),
                                                                 ('HPE', 'Hewlett Packard Enterprise', 0),
                                                                 ('HLT', 'Hilton Worldwide', 0),
                                                                 ('HOLX', 'Hologic', 0),
                                                                 ('HD', 'Home Depot (The)', 0),
                                                                 ('HON', 'Honeywell', 0),
                                                                 ('HRL', 'Hormel Foods', 0),
                                                                 ('HST', 'Host Hotels & Resorts', 0),
                                                                 ('HWM', 'Howmet Aerospace', 0),
                                                                 ('HPQ', 'HP Inc.', 0),
                                                                 ('HUBB', 'Hubbell Incorporated', 0),
                                                                 ('HUM', 'Humana', 0),
                                                                 ('HBAN', 'Huntington Bancshares', 0),
                                                                 ('HII', 'Huntington Ingalls Industries', 0),
                                                                 ('IBM', 'IBM', 0),
                                                                 ('IEX', 'IDEX Corporation', 0),
                                                                 ('IDXX', 'Idexx Laboratories', 0),
                                                                 ('ITW', 'Illinois Tool Works', 0),
                                                                 ('INCY', 'Incyte', 0),
                                                                 ('IR', 'Ingersoll Rand', 0),
                                                                 ('PODD', 'Insulet Corporation', 0),
                                                                 ('INTC', 'Intel', 0),
                                                                 ('ICE', 'Intercontinental Exchange', 0),
                                                                 ('IFF', 'International Flavors & Fragrances', 0),
                                                                 ('IP', 'International Paper', 0),
                                                                 ('IPG', 'Interpublic Group of Companies (The)', 0),
                                                                 ('INTU', 'Intuit', 0),
                                                                 ('ISRG', 'Intuitive Surgical', 0),
                                                                 ('IVZ', 'Invesco', 0),
                                                                 ('INVH', 'Invitation Homes', 0),
                                                                 ('IQV', 'IQVIA', 0),
                                                                 ('IRM', 'Iron Mountain', 0),
                                                                 ('JBHT', 'J.B. Hunt', 0),
                                                                 ('JBL', 'Jabil', 0),
                                                                 ('JKHY', 'Jack Henry & Associates', 0),
                                                                 ('J', 'Jacobs Solutions', 0),
                                                                 ('JNJ', 'Johnson & Johnson', 0),
                                                                 ('JCI', 'Johnson Controls', 0),
                                                                 ('JPM', 'JPMorgan Chase', 0),
                                                                 ('JNPR', 'Juniper Networks', 0),
                                                                 ('K', 'Kellanova', 0),
                                                                 ('KVUE', 'Kenvue', 0),
                                                                 ('KDP', 'Keurig Dr Pepper', 0),
                                                                 ('KEY', 'KeyCorp', 0),
                                                                 ('KEYS', 'Keysight Technologies', 0),
                                                                 ('KMB', 'Kimberly-Clark', 0),
                                                                 ('KIM', 'Kimco Realty', 0),
                                                                 ('KMI', 'Kinder Morgan', 0),
                                                                 ('KKR', 'KKR & Co.', 0),
                                                                 ('KLAC', 'KLA Corporation', 0),
                                                                 ('KHC', 'Kraft Heinz', 0),
                                                                 ('KR', 'Kroger', 0),
                                                                 ('LHX', 'L3Harris', 0),
                                                                 ('LH', 'Labcorp', 0),
                                                                 ('LRCX', 'Lam Research', 0),
                                                                 ('LW', 'Lamb Weston', 0),
                                                                 ('LVS', 'Las Vegas Sands', 0),
                                                                 ('LDOS', 'Leidos', 0),
                                                                 ('LEN', 'Lennar', 0),
                                                                 ('LII', 'Lennox International', 0),
                                                                 ('LLY', 'Lilly (Eli)', 0),
                                                                 ('LIN', 'Linde plc', 0),
                                                                 ('LYV', 'Live Nation Entertainment', 0),
                                                                 ('LKQ', 'LKQ Corporation', 0),
                                                                 ('LMT', 'Lockheed Martin', 0),
                                                                 ('L', 'Loews Corporation', 0),
                                                                 ('LOW', 'Lowe''s', 0),
('LULU', 'Lululemon Athletica', 0),
('LYB', 'LyondellBasell', 0),
('MTB', 'M&T Bank', 0),
('MPC', 'Marathon Petroleum', 0),
('MKTX', 'MarketAxess', 0),
('MAR', 'Marriott International', 0),
('MMC', 'Marsh McLennan', 0),
('MLM', 'Martin Marietta Materials', 0),
('MAS', 'Masco', 0),
('MA', 'Mastercard', 0),
('MTCH', 'Match Group', 0),
('MKC', 'McCormick & Company', 0),
('MCD', 'McDonald''s', 0),
                                                                 ('MCK', 'McKesson Corporation', 0),
                                                                 ('MDT', 'Medtronic', 0),
                                                                 ('MRK', 'Merck & Co.', 0),
                                                                 ('META', 'Meta Platforms', 0),
                                                                 ('MET', 'MetLife', 0),
                                                                 ('MTD', 'Mettler Toledo', 0),
                                                                 ('MGM', 'MGM Resorts', 0),
                                                                 ('MCHP', 'Microchip Technology', 0),
                                                                 ('MU', 'Micron Technology', 0),
                                                                 ('MSFT', 'Microsoft', 0),
                                                                 ('MAA', 'Mid-America Apartment Communities', 0),
                                                                 ('MRNA', 'Moderna', 0),
                                                                 ('MHK', 'Mohawk Industries', 0),
                                                                 ('MOH', 'Molina Healthcare', 0),
                                                                 ('TAP', 'Molson Coors Beverage Company', 0),
                                                                 ('MDLZ', 'Mondelez International', 0),
                                                                 ('MPWR', 'Monolithic Power Systems', 0),
                                                                 ('MNST', 'Monster Beverage', 0),
                                                                 ('MCO', 'Moody''s Corporation', 0),
('MS', 'Morgan Stanley', 0),
('MOS', 'Mosaic Company (The)', 0),
('MSI', 'Motorola Solutions', 0),
('MSCI', 'MSCI Inc.', 0),
('NDAQ', '"Nasdaq', 0),
('NTAP', 'NetApp', 0),
('NFLX', 'Netflix', 0),
('NEM', 'Newmont', 0),
('NWSA', 'News Corp (Class A)', 0),
('NWS', 'News Corp (Class B)', 0),
('NEE', 'NextEra Energy', 0),
('NKE', '"Nike', 0),
('NI', 'NiSource', 0),
('NDSN', 'Nordson Corporation', 0),
('NSC', 'Norfolk Southern', 0),
('NTRS', 'Northern Trust', 0),
('NOC', 'Northrop Grumman', 0),
('NCLH', 'Norwegian Cruise Line Holdings', 0),
('NRG', 'NRG Energy', 0),
('NUE', 'Nucor', 0),
('NVDA', 'Nvidia', 0),
('NVR', '"NVR', 0),
('NXPI', 'NXP Semiconductors', 0),
('ORLY', 'O’Reilly Automotive', 0),
('OXY', 'Occidental Petroleum', 0),
('ODFL', 'Old Dominion', 0),
('OMC', 'Omnicom Group', 0),
('ON', 'ON Semiconductor', 0),
('OKE', 'Oneok', 0),
('ORCL', 'Oracle Corporation', 0),
('OTIS', 'Otis Worldwide', 0),
('PCAR', 'Paccar', 0),
('PKG', 'Packaging Corporation of America', 0),
('PLTR', 'Palantir Technologies', 0),
('PANW', 'Palo Alto Networks', 0),
('PARA', 'Paramount Global', 0),
('PH', 'Parker Hannifin', 0),
('PAYX', 'Paychex', 0),
('PAYC', 'Paycom', 0),
('PYPL', 'PayPal', 0),
('PNR', 'Pentair', 0),
('PEP', 'PepsiCo', 0),
('PFE', 'Pfizer', 0),
('PCG', 'PG&E Corporation', 0),
('PM', 'Philip Morris International', 0),
('PSX', 'Phillips 66', 0),
('PNW', 'Pinnacle West Capital', 0),
('PNC', 'PNC Financial Services', 0),
('POOL', 'Pool Corporation', 0),
('PPG', 'PPG Industries', 0),
('PPL', 'PPL Corporation', 0),
('PFG', 'Principal Financial Group', 0),
('PG', 'Procter & Gamble', 0),
('PGR', 'Progressive Corporation', 0),
('PLD', 'Prologis', 0),
('PRU', 'Prudential Financial', 0),
('PEG', 'Public Service Enterprise Group', 0),
('PTC', 'PTC Inc.', 0),
('PSA', 'Public Storage', 0),
('PHM', 'PulteGroup', 0),
('PWR', 'Quanta Services', 0),
('QCOM', 'Qualcomm', 0),
('DGX', 'Quest Diagnostics', 0),
('RL', 'Ralph Lauren Corporation', 0),
('RJF', 'Raymond James Financial', 0),
('RTX', 'RTX Corporation', 0),
('O', 'Realty Income', 0),
('REG', 'Regency Centers', 0),
('REGN', 'Regeneron Pharmaceuticals', 0),
('RF', 'Regions Financial Corporation', 0),
('RSG', 'Republic Services', 0),
('RMD', 'ResMed', 0),
('RVTY', 'Revvity', 0),
('ROK', 'Rockwell Automation', 0),
('ROL', '"Rollins', 0),
('ROP', 'Roper Technologies', 0),
('ROST', 'Ross Stores', 0),
('RCL', 'Royal Caribbean Group', 0),
('SPGI', 'S&P Global', 0),
('CRM', 'Salesforce', 0),
('SBAC', 'SBA Communications', 0),
('SLB', 'Schlumberger', 0),
('STX', 'Seagate Technology', 0),
('SRE', 'Sempra', 0),
('NOW', 'ServiceNow', 0),
('SHW', 'Sherwin-Williams', 0),
('SPG', 'Simon Property Group', 0),
('SWKS', 'Skyworks Solutions', 0),
('SJM', 'J.M. Smucker Company (The)', 0),
('SW', 'Smurfit Westrock', 0),
('SNA', 'Snap-on', 0),
('SOLV', 'Solventum', 0),
('SO', 'Southern Company', 0),
('LUV', 'Southwest Airlines', 0),
('SWK', 'Stanley Black & Decker', 0),
('SBUX', 'Starbucks', 0),
('STT', 'State Street Corporation', 0),
('STLD', 'Steel Dynamics', 0),
('STE', 'Steris', 0),
('SYK', 'Stryker Corporation', 0),
('SMCI', 'Supermicro', 0),
('SYF', 'Synchrony Financial', 0),
('SNPS', 'Synopsys', 0),
('SYY', 'Sysco', 0),
('TMUS', 'T-Mobile US', 0),
('TROW', 'T. Rowe Price', 0),
('TTWO', 'Take-Two Interactive', 0),
('TPR', '"Tapestry', 0),
('TRGP', 'Targa Resources', 0),
('TGT', 'Target Corporation', 0),
('TEL', 'TE Connectivity', 0),
('TDY', 'Teledyne Technologies', 0),
('TFX', 'Teleflex', 0),
('TER', 'Teradyne', 0),
('TSLA', '"Tesla', 0),
('TXN', 'Texas Instruments', 0),
('TPL', 'Texas Pacific Land Corporation', 0),
('TXT', 'Textron', 0),
('TMO', 'Thermo Fisher Scientific', 0),
('TJX', 'TJX Companies', 0),
('TSCO', 'Tractor Supply', 0),
('TT', 'Trane Technologies', 0),
('TDG', 'TransDigm Group', 0),
('TRV', 'Travelers Companies (The)', 0),
('TRMB', 'Trimble Inc.', 0),
('TFC', 'Truist Financial', 0),
('TYL', 'Tyler Technologies', 0),
('TSN', 'Tyson Foods', 0),
('USB', 'U.S. Bancorp', 0),
('UBER', 'Uber', 0),
('UDR', '"UDR', 0),
('ULTA', 'Ulta Beauty', 0),
('UNP', 'Union Pacific Corporation', 0),
('UAL', 'United Airlines Holdings', 0),
('UPS', 'United Parcel Service', 0),
('URI', 'United Rentals', 0),
('UNH', 'UnitedHealth Group', 0),
('UHS', 'Universal Health Services', 0),
('VLO', 'Valero Energy', 0),
('VTR', 'Ventas', 0),
('VLTO', 'Veralto', 0),
('VRSN', 'Verisign', 0),
('VRSK', 'Verisk Analytics', 0),
('VZ', 'Verizon', 0),
('VRTX', 'Vertex Pharmaceuticals', 0),
('VTRS', 'Viatris', 0),
('VICI', 'Vici Properties', 0),
('V', 'Visa Inc.', 0),
('VST', 'Vistra Corp.', 0),
('VMC', 'Vulcan Materials Company', 0),
('WRB', 'W. R. Berkley Corporation', 0),
('GWW', 'W. W. Grainger', 0),
('WAB', 'Wabtec', 0),
('WBA', 'Walgreens Boots Alliance', 0),
('WMT', 'Walmart', 0),
('DIS', 'Walt Disney Company (The)', 0),
('WBD', 'Warner Bros. Discovery', 0),
('WM', 'Waste Management', 0),
('WAT', 'Waters Corporation', 0),
('WEC', 'WEC Energy Group', 0),
('WFC', 'Wells Fargo', 0),
('WELL', 'Welltower', 0),
('WST', 'West Pharmaceutical Services', 0),
('WDC', 'Western Digital', 0),
('WY', 'Weyerhaeuser', 0),
('WMB', 'Williams Companies', 0),
('WTW', 'Willis Towers Watson', 0),
('WDAY', '"Workday', 0),
('WYNN', 'Wynn Resorts', 0),
('XEL', 'Xcel Energy', 0),
('XYL', 'Xylem Inc.', 0),
('YUM', 'Yum! Brands', 0),
('ZBRA', 'Zebra Technologies', 0),
('ZBH', 'Zimmer Biomet', 0),
('ZTS', 'Zoetis', 0);
