-- Insert initial stock data with current_price set to 0

INSERT INTO stock (ticker_symbol, stock_name, current_price)
VALUES
    ('AAPL', 'Apple Inc.', 0),
    ('MSFT', 'Microsoft Corporation', 0),
    ('GOOGL', 'Alphabet Inc.', 0),
    ('AMZN', 'Amazon.com Inc.', 0),
    ('TSLA', 'Tesla Inc.', 0),
    ('META', 'Meta Platforms Inc.', 0),
    ('NVDA', 'NVIDIA Corporation', 0),
    ('UNH', 'UnitedHealth Group Incorporated', 0),
    ('V', 'Visa Inc.', 0),
    ('JNJ', 'Johnson & Johnson', 0),
    ('JPM', 'JPMorgan Chase & Co.', 0),
    ('PFE', 'Pfizer Inc.', 0),
    ('MA', 'Mastercard Incorporated', 0),
    ('HD', 'Home Depot Inc.', 0),
    ('DIS', 'The Walt Disney Company', 0),
    ('PYPL', 'PayPal Holdings Inc.', 0),
    ('VZ', 'Verizon Communications Inc.', 0),
    ('NFLX', 'Netflix Inc.', 0),
    ('CSCO', 'Cisco Systems Inc.', 0),
    ('INTC', 'Intel Corporation', 0),
    ('MRK', 'Merck & Co., Inc.', 0),
    ('XOM', 'Exxon Mobil Corporation', 0),
    ('BA', 'The Boeing Company', 0),
    ('WMT', 'Walmart Inc.', 0),
    ('MCD', 'McDonald''s Corporation', 0),
    ('KO', 'The Coca-Cola Company', 0),
    ('CAT', 'Caterpillar Inc.', 0),
    ('IBM', 'International Business Machines Corporation', 0),
    ('ABT', 'Abbott Laboratories', 0),
    ('LLY', 'Eli Lilly and Company', 0),
    ('MS', 'Morgan Stanley', 0),
    ('GS', 'Goldman Sachs Group Inc.', 0),
    ('NKE', 'Nike Inc.', 0),
    ('HON', 'Honeywell International Inc.', 0),
    ('AMGN', 'Amgen Inc.', 0),
    ('BMY', 'Bristol-Myers Squibb Company', 0),
    ('MMM', '3M Company', 0),
    ('TMO', 'Thermo Fisher Scientific Inc.', 0),
    ('MDT', 'Medtronic plc', 0),
    ('SBUX', 'Starbucks Corporation', 0),
    ('LMT', 'Lockheed Martin Corporation', 0),
    ('DHR', 'Danaher Corporation', 0),
    ('CVX', 'Chevron Corporation', 0),
    ('SPG', 'Simon Property Group Inc.', 0)
ON CONFLICT (ticker_symbol) DO NOTHING;
